src/components/TasksCard/index.tsx
src/components/TasksCard/styled.tsx
src/theme/mainTheme.tsx

- added TasksCard component
- additionally updated theme:  added grey colors from figma project, changed 'shadows' property,  added new typography variant (capitalHeader), changed borderRadius to 8px;
The theme update is just a draft and perhaps it's too early to change it now but it's easy to get back to the previous version if you don't like it 😄

P2022 188 tasks card

---

src/components/PageHeader/PageHeader.style.tsx
src/components/PageHeader/PageHeader.tsx

Fixed version of Header component

[P2022-185] Header component

---

src/components/Button/Button.style.tsx
src/components/Button/Button.tsx
src/theme/mainTheme.ts
src/views/SecondPage/SecondPage.tsx

Remove 'style' prop & theme fix but please check the theme. Does it renders 8px borderRadius for you.

P2022 182 button

---

src/theme/mainTheme.ts

https://tracker.intive.com/jira/browse/P2022-687

[P2022-687] Shadows fix in theme

---

src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx

Button Story. Not all props from MUI are working, so I suspect I'll need an update on that. For now  'long' & 'children' work as suspected, 'variant' prop only works on 'text' & 'contained'

[P2022-477] add Button Story

---

src/components/TasksCard/TasksCard.stories.tsx
src/components/TasksCard/styled.tsx
src/components/Ticket/Ticket.style.tsx

Jira: https://tracker.intive.com/jira/browse/P2022-480

P2022-480 add taskscard with tickets story

---

src/App.tsx
src/components/NewProjectDialog/NewProjectDialog.tsx
src/components/Select/Select.tsx
src/views/Projects/Projects.style.tsx
src/views/Projects/Projects.tsx
src/views/SecondPage/SecondPage.style.tsx
src/views/SecondPage/SecondPage.tsx

- set flex direction to column in secondary page
- adjusted margins and containers widths for better user experience
- render select for language change possibility
- secondary page now has a link to projects view

prepare project for presentation

---

src/components/ConfirmationDialog/ConfirmationDialog.stories.tsx
src/components/ConfirmationDialog/ConfirmationDialog.tsx
src/translations/en.json
src/translations/pl.json

[Jira-Link](https://tracker.intive.com/jira/browse/P2022-1130) Confirmation Dialog based on BasicModal with story

[P2022-1130] confirmation dialog

---

src/components/PageHeader/PageHeader.style.tsx

[JiraLink](https://tracker.intive.com/jira/browse/P2022-1222?filter=-1) Fixed styles for button used in PageHeader component & changed Mui Button for custom Button component import.

[P2022-1222] Fix styles & import

---

src/components/Input/Input.style.tsx
src/components/Input/Input.tsx
src/stories/Input.stories.tsx
src/views/OwlInput/OwlInput.tsx

Finished last fixes to Input component.

P2022 1220 fixes to input

---

src/components/NewProjectDialog/NewProjectDialog.tsx
src/modules/WelcomeScreen/WelcomeScreen.tsx
src/views/SecondPage/SecondPage.tsx

https://tracker.intive.com/jira/browse/P2022-1126

P2022-1126

---

src/components/BasicModal/BasicModal.style.tsx
src/components/Input/Input.style.tsx
src/components/Input/Input.tsx
src/components/Select/Select.style.tsx
src/components/Select/Select.tsx
src/hooks/useForm.tsx
src/modules/CreateIssueDialog/CreateIssueDialog.style.tsx
src/modules/CreateIssueDialog/CreateIssueDialog.tsx
src/translations/en.json
src/translations/pl.json
src/validation/validateCreateIssue.ts
src/views/SecondPage/SecondPage.tsx

[https://tracker.intive.com/jira/browse/P2022-1133](url)

[P2022-1133] create issue dialog

---

package.json
src/api/makeFetchRequest.ts
src/api/projects/mockProjectsApi.ts
src/api/projects/projectsApi.ts
src/mockData/mockProjects.ts
src/views/Projects/Projects.tsx

[JIRA](https://tracker.intive.com/jira/browse/P2022-1123)

[P2022-1123]_mocking-mechanism

---

src/components/Navbar/Navbar.style.tsx
src/components/Navbar/Navbar.tsx

https://tracker.intive.com/jira/browse/P2022-1187
Zmiana typu komponentu z MUI ikon w Navbarze na typ IconButton i dodanie ich odpowiedniego stylowania (zachowanie wyglądu aplikacji, rozszerzenie komponentów o "klikalność")

P2022 1187 change type icons in Navbar

---

cypress/integration/createProject.spec.ts

[JiraLink](https://tracker.intive.com/jira/browse/P2022-1129) E2E test going through process of creating new project.

[P2022-1129] Create new project test

---

src/components/ThreeDotsMenu/ThreeDotsMenu.style.tsx
src/components/ThreeDotsMenu/ThreeDotsMenu.tsx
src/theme/mainTheme.ts

[https://tracker.intive.com/jira/browse/P2022-1194](https://tracker.intive.com/jira/browse/P2022-1194)
- inserted label text into Typography component and changed color to #626262
- removed leftover white spaces on hover
SWEET BONUS:
-tertiary custom shadow ;)

[P2022-1194] 3 dots menu corrections

---

src/components/Input/Input.style.tsx
src/modules/NewProjectDialog/NewProjectDialog.style.tsx
src/modules/NewProjectDialog/NewProjectDialog.tsx
src/theme/mainTheme.ts

[https://tracker.intive.com/jira/browse/P2022-1197](https://tracker.intive.com/jira/browse/P2022-1197)
Changes:
- changed dialog title color and text color in text button to #515151
- changed input error helper text positioning from absolute to default
- changed background color of the input to #F7F7F7

[P2022-1197] corrections to newProjectDialog

---

src/components/ThreeDotsMenu/ThreeDotsMenu.style.tsx
src/modules/TasksCard/styled.tsx
src/modules/Ticket/Ticket.style.tsx

Jira: https://tracker.intive.com/jira/browse/P2022-1218
Add changes in styling of component Ticket

add corrections to component Ticket

---

src/translations/en.json
src/translations/pl.json
src/views/BoardList/BoardsList.tsx

https://tracker.intive.com/jira/browse/P2022-1390
Adding a new board integrated with API.

P2022 1390 add board with api

---

src/modules/CreateIssueDialog/CreateIssueDialog.tsx

I forgot to stage these changes on my last commit

[P2022-1409] fix error messages and error color in createIssueDialog component

---

src/api/boards/boardsApi.ts
src/modules/NewBoardDialog/NewBoardDialog.style.tsx
src/modules/NewBoardDialog/NewBoardDialog.tsx
src/views/BoardList/BoardsList.tsx

Redone the integration with API - adding a new board.
Added a new component NewBoardDialog

redone integration with API - adding a new board

---

src/api/boardStatus/mockBoardStatusApi.ts
src/api/contsans.tsx
src/api/requestsApi.ts
src/hooks/useAlerts.tsx
src/modules/TasksCard/TasksCard.stories.tsx
src/modules/Ticket/Ticket.tsx
src/translations/en.json
src/translations/pl.json
src/views/Board/Board.tsx

[https://tracker.intive.com/jira/browse/P2022-1394](https://tracker.intive.com/jira/browse/P2022-1394)
- added api integration  - deleting issues from column
- added useAlerts custom hook for managing alerts in cleaner way

[P2022-1394] api integration delete issue from column

---

src/api/contsans.tsx
src/api/requestsApi.ts
src/views/IssueDetails/IssueDetails.tsx

[https://tracker.intive.com/jira/browse/P2022-1713](https://tracker.intive.com/jira/browse/P2022-1713)

[P2022-1713] api integration: change assignee in issue details

---

src/api/contsans.tsx
src/views/BoardList/BoardsList.tsx

[https://tracker.intive.com/jira/browse/P2022-2044](https://tracker.intive.com/jira/browse/P2022-2044)

[P2022-2044] download list of boards based on projectId

---

src/views/IssueDetails/IssueDetails.tsx

I had forgotten to push necessary changes to branch P2022-1713 before it was merged to main

hotfix related to [P2022-1713] adjust assigning user to issue logic to recent api changes

---

src/App.tsx
src/api/boards/mockBoardsApi.ts
src/api/contsans.tsx
src/modules/BoardsList/BoardsList.tsx
src/translations/en.json
src/translations/pl.json
src/views/BoardListView/BoardsListView.style.tsx
src/views/BoardListView/BoardsListView.tsx

[JiraLink](https://tracker.intive.com/jira/browse/P2022-1391?filter=-1)
For now integration only on Bards List view

[P2022-1391]R emove board api integration

---

src/api/boards/mockBoardsApi.ts
src/api/contsans.tsx
src/mockData/mocBoardsList.tsx
src/translations/en.json
src/translations/pl.json
src/views/BoardListView/BoardsListView.tsx
src/views/IssueDetails/IssueDetails.tsx

[https://tracker.intive.com/jira/browse/P2022-2042](https://tracker.intive.com/jira/browse/P2022-2042)
- adjusted api integration (adding new board) to recent Board endpoint changes
- included some additional smaller changes related to other components aswell - fixing board list downloading in mock mode, going back to board view from issue details view

[P2022-2042] refactor create new board api integration

---

src/translations/i18n.tsx

- polish is a default app language
- if en or en-US languages are set in browser settings then app is displayed in english

[P2022-2040] display app language based on browser language settings

---

src/modules/BoardsList/BoardsList.tsx
src/modules/ProjectsList/ProjectsList.tsx
src/views/Projects/Projects.tsx

- removed it from board card aswell

[P2022-2061] delete add column option from three dots menu in project card
